  mydb:
    driver : SQL Server Native Client 11.0
    server : MAHESHDASARI
    database : Mahesh
  data_file_path : 'D:\Project_EDM\Project_emp_data\DT=2022-07-15\HR=10\Employee_V1.csv'
  SQLS:
    DDL :
      - 'D:\Project_EDM\SQL\Onetime\file_load\create_raw_emp_tbl.sql'
      - 'D:\Project_EDM\SQL\Onetime\table_load\create_final_emp_tbl.sql'
    DML :
      - 'D:\Project_EDM\SQL\Onetime\file_load\insert_raw_emp_tbl.sql'
      - 'D:\Project_EDM\SQL\Onetime\table_load\insert_final_emp_tbl.sql'

